waypoint_follower:
  ros__parameters:
    loop_rate: 20.0
    stop_on_failure: false
    waypoint_task_executor_plugin: "input_at_waypoint"
    input_at_waypoint:
      plugin: "nav2_waypoint_follower::InputAtWaypoint"
      input_topic: "/waypoint_task_trigger"
      wait_timeout: 10.0