twist_mux:
  ros__parameters:
    use_stamped: false
    topics: 
      joystick:
        topic: joy_vel
        priority: 99
        timeout: 0.5
      keyboard:
        topic: key_vel
        priority: 90
        timeout: 0.5